import test from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {persistPcOwnerPlan,preparePcOwnerPlanFromEnvironment,restrictOwnedDirectoryWrite} from './pc-owner-environment-plan.mjs';
function fixture(){const mount=fs.mkdtempSync(path.join(os.tmpdir(),'jh-plan-'));fs.chmodSync(mount,0o700);return {p:{version:1,serverOrigin:'https://jh-secure-bridge-fix4.onrender.com',googleWebClientId:'test-web.apps.googleusercontent.com',androidClientId:'test-android.apps.googleusercontent.com',expectedGmail:'synthetic@gmail.com',ownerLabel:'Synthetic',storageMount:mount,storageEpoch:'synthetic-epoch-001'},cleanup:()=>fs.rmSync(mount,{recursive:true,force:true})};}
test('explicit plan is private, read back, and repeated publication does not rewrite',()=>{const f=fixture();try{const r=persistPcOwnerPlan(f.p);assert.equal(r.created,true);assert.equal(r.authorityGranted,false);const file=path.join(f.p.storageMount,'jh-pc-bootstrap/plan.json'),first=fs.readFileSync(file),before=fs.statSync(file);assert.equal(before.mode&0o777,0o600);assert.equal(fs.statSync(path.dirname(file)).mode&0o777,0o700);assert.equal(persistPcOwnerPlan(f.p).created,false);assert.deepEqual(fs.readFileSync(file),first);assert.equal(fs.statSync(file).mtimeMs,before.mtimeMs);}finally{f.cleanup();}});
test('different operator plan cannot replace existing settings',()=>{const f=fixture();try{persistPcOwnerPlan(f.p);assert.throws(()=>persistPcOwnerPlan({...f.p,expectedGmail:'other@gmail.com'}),/PC_PLAN_EXISTING_CONFIG_CONFLICT/);}finally{f.cleanup();}});
for(const item of ['.plan-writing','.plan-stage'])test('interrupted '+item+' is preserved for review',()=>{const f=fixture();try{const d=path.join(f.p.storageMount,'jh-pc-bootstrap');fs.mkdirSync(d,{mode:0o700});fs.writeFileSync(path.join(d,item),'interrupted',{mode:0o600});assert.throws(()=>persistPcOwnerPlan(f.p),/PC_PLAN_INTERRUPTED_REVIEW_REQUIRED/);assert.equal(fs.readFileSync(path.join(d,item),'utf8'),'interrupted');}finally{f.cleanup();}});
test('linked private directory is rejected',()=>{const f=fixture();try{fs.mkdirSync(path.join(f.p.storageMount,'other'),{mode:0o700});fs.symlinkSync('other',path.join(f.p.storageMount,'jh-pc-bootstrap'));assert.throws(()=>persistPcOwnerPlan(f.p),/PC_PLAN_PRIVATE_DIRECTORY_REQUIRED/);}finally{f.cleanup();}});
test('linked plan file is rejected',()=>{const f=fixture();try{persistPcOwnerPlan(f.p);const d=path.join(f.p.storageMount,'jh-pc-bootstrap');fs.renameSync(path.join(d,'plan.json'),path.join(d,'other'));fs.symlinkSync('other',path.join(d,'plan.json'));assert.throws(()=>persistPcOwnerPlan(f.p));}finally{f.cleanup();}});
test('nonprivate plan file is rejected',()=>{const f=fixture();try{persistPcOwnerPlan(f.p);fs.chmodSync(path.join(f.p.storageMount,'jh-pc-bootstrap/plan.json'),0o644);assert.throws(()=>persistPcOwnerPlan(f.p));}finally{f.cleanup();}});
test('no environmental plan has no write effect',()=>assert.deepEqual(preparePcOwnerPlanFromEnvironment({}),{materialized:false}));
test('environment provision is explicit and never accepts a temporary production mount',()=>{const f=fixture();try{const json=JSON.stringify(f.p);assert.throws(()=>preparePcOwnerPlanFromEnvironment({JH_PC_OWNER_SETUP_PLAN_JSON:json}),/PC_SETUP_EXPLICIT_ENABLE_REQUIRED/);assert.throws(()=>preparePcOwnerPlanFromEnvironment({JH_PC_OWNER_SETUP_ENABLED:'1',JH_PC_OWNER_SETUP_PLAN_FILE:'/var/data/jh-pc-bootstrap/plan.json',JH_PC_OWNER_SETUP_PLAN_JSON:json}),/PC_SETUP_PRODUCTION_MOUNT_REQUIRED/);assert.equal(fs.readdirSync(f.p.storageMount).length,0);}finally{f.cleanup();}});
test('malformed, duplicate and extra fields cannot become a private plan',()=>{const env={JH_PC_OWNER_SETUP_ENABLED:'1',JH_PC_OWNER_SETUP_PLAN_FILE:'/var/data/jh-pc-bootstrap/plan.json'};for(const value of ['{}','{"version":1,"version":1}','x'.repeat(8193)])assert.throws(()=>preparePcOwnerPlanFromEnvironment({...env,JH_PC_OWNER_SETUP_PLAN_JSON:value}),/PC_PLAN_ENVIRONMENT_INVALID/);});

test('owned directory permission preparation only removes other-user write bits',()=>{const f=fixture();try{const child=path.join(f.p.storageMount,'existing-user-data');fs.writeFileSync(child,'unchanged');fs.chmodSync(child,0o644);const before=fs.statSync(child);fs.chmodSync(f.p.storageMount,0o777);const r=restrictOwnedDirectoryWrite(f.p.storageMount);assert.deepEqual(r,{permissionsTightened:true,beforeMode:'777',afterMode:'755',childrenChanged:false});assert.equal(fs.readFileSync(child,'utf8'),'unchanged');assert.equal(fs.statSync(child).mode,before.mode);assert.equal(fs.statSync(child).mtimeMs,before.mtimeMs);assert.equal(restrictOwnedDirectoryWrite(f.p.storageMount).permissionsTightened,false);}finally{f.cleanup();}});
test('mount preparation rejects symlinks and leaves target untouched',()=>{const f=fixture();try{const dir=path.join(f.p.storageMount,'dir');fs.mkdirSync(dir,{mode:0o777});fs.chmodSync(dir,0o777);fs.symlinkSync('dir',path.join(f.p.storageMount,'link'));assert.throws(()=>restrictOwnedDirectoryWrite(path.join(f.p.storageMount,'link')),/PC_MOUNT_OWNER_REVIEW_REQUIRED/);assert.equal(fs.statSync(dir).mode&0o777,0o777);}finally{f.cleanup();}});
test('already private directory remains private',()=>{const f=fixture();try{assert.deepEqual(restrictOwnedDirectoryWrite(f.p.storageMount),{permissionsTightened:false,beforeMode:'700',afterMode:'700',childrenChanged:false});}finally{f.cleanup();}});
